---
name: Deploy ResolVI Nextflow to Amazon ECR
on:
  push:
    branches: [prod]
    paths: [nextflow/resolvinf/scanpy_scvi_decoupler/0.0.0/**]
env:
  AWS_REGION: us-east-1
  REGISTRY_ALIAS: chobiolab
  REPOSITORY: resolvinf
  VER: 0.0.0
  BUILD_PATH: nextflow/resolvinf/scanpy_scvi_decoupler/0.0.0
permissions:
  contents: read
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      # added this line to shorten the SHA tag
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-7`" >> $GITHUB_ENV
      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        run: |-
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$VER $BUILD_PATH
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$VER
